[secrets]
weather_api_key = """
hF4DHWJUjMfAyJ8SAQdAXiixQxMIt9ctKOXck44Y0iiYBH0jjNWvFyJe8biBw2kw
SfU7HFkTOHvmd7msoCEUZxFbz8iDU1ajLG/7R8+TwDE/RAUYSnF1gAQ8eL1KnVBP
0lsBbJc9DPFWmMAZmpa5MgUO8HRANCiBVAoLaTHOOgCb4Mnbjpf6LCUWP1xz8Jky
lyV4PpGiHMqCI7qzNZk9utT4o6kLQZa+10IjptzPp44uDNe7nvDE6Uo7urWk
=FQQa
"""
